### ISSUE TITLE
Remove enchantment descriptions

### ISSUE THREAD

**Issue by CalaMariGold** [Ellpeck/Nyx#35] opened 2020-10-01 20:17 UTC
Overlaps with enchantment descriptions mod

**Comment by l4ssc** [comment] 2020-10-03 00:25
Duplicate of #19, but I [made a fork to implement exactly this](https://github.com/l4ssc/Nyx). Willing to PR if @Ellpeck is okay with it.

**Closed** 2020-10-03 19:31 UTC
