### ISSUE TITLE
Light source from fallen star doesn't get removed

### ISSUE THREAD

**Issue by CalaMariGold** [Ellpeck/Nyx#12] opened 2020-03-26 23:59 UTC
When a fallen star despawns, the light source is still there and can't be removed.

**Comment by Ellpeck** [comment] 2020-03-28 14:47
I am unable to reproduce this. The block that creates the light source is removed every time in my testing.

What you might be experiencing is the regularly occuring vanilla issue of light not properly propagating throughout the world (which is the same sort of issue that creates huge dark spots below small world gen overhangs etc). That's easily fixed by just placing any kind of light source in the area that's lit up and then removing it again, though.   
If that's the case, then you can close this issue, since that is not something I can fix in Nyx.

**Closed** 2020-03-30 00:55 UTC
